# Generated by Django 2.1.5 on 2020-01-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuetest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='images/', verbose_name='图片'),
        ),
    ]
